# Generated by Django 4.1.7 on 2023-04-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=255)),
                ('op1', models.CharField(max_length=255)),
                ('op2', models.CharField(max_length=255)),
                ('op3', models.CharField(max_length=255)),
                ('op4', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255)),
            ],
        ),
    ]
