# Generated by Django 4.0.3 on 2023-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog1', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
